Fix issue #8
laminas/laminas-escaper pull request #9
Opened 2020-10-04 20:52 UTC by Gounlaf

This PR should check all tasks in #8

2020-10-05 18:24 UTC, Gounlaf commented
Have to rollback typehinting (BC Break)

2020-10-16 01:28 UTC, andypost approved these changes
Looks great and pass tests

2020-10-16 07:04 UTC, froschdesign requested changes
> Have to rollback typehinting (BC Break)

A rollback is correct here.

2020-10-16 07:08 UTC, Gounlaf commented
> > Have to rollback typehinting (BC Break)
> 
> A rollback is correct here.

It as a reminder. I pushed another commit after that to do the rollback as required 🙂

2020-10-16 07:10 UTC, froschdesign commented
@Gounlaf 
Take your time and many thanks for your help! 👍 👍 👍

2020-10-16 11:13 UTC, Gounlaf commented
I've reverted changes related to typehinting, and squash.

2020-10-16 16:32 UTC, boesing approved these changes
LGTM.
I'd prefer having the `vendor/phpunit/phpunit/phpunit.xsd` instead for the schema ref but imho thats not a showstopper.

2020-10-18 16:13 UTC, Gounlaf commented
> LGTM.
> I'd prefer having the `vendor/phpunit/phpunit/phpunit.xsd` instead for the schema ref but imho thats not a showstopper.

I can change it if you want

2020-11-01 14:53 UTC, andypost commented
Is ghere release schedule for PHP 8 support? 
Drupal 9.1 (upcoming release) has it as dev-dependency and it's a blocker to declare PHP 8 support

2020-11-01 19:05 UTC, froschdesign requested changes

2020-11-01 19:05 UTC, froschdesign commented on phpunit.xml.dist
> +         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd"
Please revert this and use the XML schema definition from the `vendor` directory of PHPUnit.

2020-11-01 19:05 UTC, froschdesign commented on test/EscaperTest.php
> +        $this->expectException(\Laminas\Escaper\Exception\InvalidArgumentException::class);
Please import the class name.

2020-11-01 19:05 UTC, froschdesign commented on test/EscaperTest.php
> +        $this->expectException(\Laminas\Escaper\Exception\InvalidArgumentException::class);
The same here.

2020-11-01 19:05 UTC, froschdesign commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
We use the option for dependencies also for nightly versions
```yaml
    - php: nightly
      env:
        - DEPS=lowest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
    - php: nightly
      env:
        - DEPS=latest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
```

2020-11-01 19:19 UTC, Gounlaf commented
@froschdesign I have commited changes according to your review.
I will squash once it's OK

2020-11-01 19:20 UTC, froschdesign commented
@Gounlaf 
You are fast! 😃 👍

2020-11-01 19:20 UTC, froschdesign approved these changes

2020-11-01 19:22 UTC, Gounlaf commented
> @Gounlaf
> You are fast! 😃 👍

:)

I can squash so?

2020-11-01 19:26 UTC, andypost approved these changes
Looks great 👍

2020-11-17 21:17 UTC, merged

2020-11-17 21:17 UTC, boesing commented
Thanks, @Gounlaf!